const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');const helmet=require('helmet');const rateLimit=require('express-rate-limit');require('dotenv').config();
const app=express(),PORT=process.env.PORT||3000,DATA=path.join(__dirname,'data','content.json'),SECRET=process.env.JWT_SECRET;
if(!SECRET||SECRET.length<32)throw new Error('Set JWT_SECRET (32+ chars)');if(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD)throw new Error('Set ADMIN_EMAIL and ADMIN_PASSWORD');
const defaults={services:[['Art & Coloring','Creative drawing and coloring time.'],['Zumba & Dancing','Music, movement and energetic fun.'],['Educational Games','Play-based learning for curious minds.'],['Skill Development','Activities that encourage new skills.'],['Clean & Safe','A welcoming environment with a professional team.']].map(([title,description],i)=>({id:'svc'+i,title,description,published:true})),prices:[['Per Hour','AED 20','1 hour of play'],['30 Hours','AED 520','Great value'],['42 Hours','AED 620','More playtime'],['64 Hours','AED 800','Best for regular visits'],['UNLIMITED HOURS','AED 1,400','For maximum flexibility']].map(([title,price,description],i)=>({id:'p'+i,title,price,description,published:true})),gallery:[],birthday:[{id:'b1',title:'Birthday Package',price:'AED 300',description:'Birthday enquiries via WhatsApp.',published:true}]};
function init(){if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(defaults,null,2));}function read(){init();return JSON.parse(fs.readFileSync(DATA));}function write(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2));}
function token(p){const b=Buffer.from(JSON.stringify(p)).toString('base64url');const s=crypto.createHmac('sha256',SECRET).update(b).digest('base64url');return b+'.'+s;}function verify(t){try{const[a,s]=t.split('.');const e=crypto.createHmac('sha256',SECRET).update(a).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const p=JSON.parse(Buffer.from(a,'base64url'));return p.exp>Date.now()?p:null;}catch{return null}}
function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!verify(t))return res.status(401).json({error:'Unauthorized'});next();}
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true,limit:'1mb'}));app.use(rateLimit({windowMs:15*60*1000,max:300}));const loginLimit=rateLimit({windowMs:15*60*1000,max:10});
app.get('/api/health',(q,r)=>r.json({ok:true,service:'rudhat-alsaadah-api'}));app.get('/api/content',(q,r)=>{const d=read();r.json(Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v.filter(x=>x.published)])));});
app.post('/api/auth/login',loginLimit,(req,res)=>{if(req.body?.email!==process.env.ADMIN_EMAIL||req.body?.password!==process.env.ADMIN_PASSWORD)return res.status(401).json({error:'Invalid credentials'});res.json({token:token({email:req.body.email,exp:Date.now()+8*60*60*1000})});});
app.get('/api/admin/content',auth,(q,r)=>r.json(read()));app.post('/api/admin/items',auth,(req,res)=>{const{type,title,description='',price='',published=true}=req.body||{};if(!['services','prices','gallery','birthday'].includes(type)||!String(title||'').trim())return res.status(400).json({error:'Invalid type/title'});const d=read(),item={id:crypto.randomUUID(),title:String(title).trim(),description:String(description),price:String(price),published:Boolean(published)};d[type].push(item);write(d);res.status(201).json(item);});
app.put('/api/admin/items/:type/:id',auth,(req,res)=>{const d=read(),a=d[req.params.type],i=a?.find(x=>x.id===req.params.id);if(!i)return res.status(404).json({error:'Not found'});for(const k of ['title','description','price','published'])if(req.body[k]!==undefined)i[k]=req.body[k];write(d);res.json(i);});app.delete('/api/admin/items/:type/:id',auth,(req,res)=>{const d=read(),a=d[req.params.type];if(!a)return res.status(404).json({error:'Not found'});const n=a.length;d[req.params.type]=a.filter(x=>x.id!==req.params.id);if(n===d[req.params.type].length)return res.status(404).json({error:'Not found'});write(d);res.json({ok:true});});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('Rudhat running on '+PORT));
